// <auto-generated />
namespace nmct.ssa.webapp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class databasemigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(databasemigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201501051620214_databasemigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
